pluginManagement {
    repositories {
        mavenLocal()
        maven {
            url = 'https://frcmaven.wpi.edu/artifactory/ex-gradle'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id "org.wpilib.WPILibVersioningPlugin" version "2027.0.1" apply false
}

gradle.beforeProject { project ->
    project.plugins.apply("org.wpilib.WPILibVersioningPlugin")
    project.wpilibVersioning.buildServerMode = project.hasProperty('buildServer')
}
